### ISSUE TITLE
Place SOS CV locations in map

### ISSUE THREAD

**Issue by LauraPirgie** [beetwo/toucan#119]
Wie können wir euch helfen bzw. was muss von unserer Seite vorbereitet werden, damit man die Standorte von SOS Kinderdörfern in der Karte drin hat? 

<img width="521" alt="bildschirmfoto 2018-02-23 um 12 07 58" src="https://user-images.githubusercontent.com/26089166/36591411-39cd38b8-1892-11e8-884c-f0b3717a582d.png">

**Comment by mcallistersean** [comment]
Kann man irgendwoher eine Liste der Kinderdoerfer auftreiben? 
Idealerweise mit Koordinaten, Adressen wuerden aber wohl auch reichen, dann muss man die halt geokodieren. Wenn das jemand machen will kann das auch gerne via google docs oder so passieren

**Comment by mcallistersean** [comment]
In dem von mir verlinktem File sind 552 Doerfer in 140 Laendern.  Das koennte hinkommen und sollte leicht zu erledigen sein.
Aber: 
Ist das eine Organisation mit 552 Locations?
Oder pro Land eine Organisation? (zB Oesterreich, 11 Locations)
Oder ist das ueberhaupt ganz was anderes ....

**Comment by LauraPirgie** [comment]
Ok gute Fragen, wir besprechen das nochmal mit SOS CV.
