### ISSUE TITLE
replace issue with need

### ISSUE THREAD

**Issue by mcallistersean** [beetwo/toucan#66]
```sed 's/issue/need/g'```

Replace all occurences of the word issue with need. This seems to be the common term in the humanitarian sector.

**Comment by fadr** [comment]
We’ve done that in the interface right? Code inspectors will see issues, though. But this can be closed as well methinks.

**Comment by mcallistersean** [comment]
Ok, if somebody else finds mentions of issue(-s) in the interface please open a new bug report.
