### ISSUE TITLE
Landingpage auf toucan.beetwo.at

### ISSUE THREAD

**Issue by LauraPirgie** [beetwo/toucan#68]
- Learn more durch Download Factsheet ersetzen

**Comment by LauraPirgie** [comment]
Neue Landingpage nicht auf toucan.beetwo.at online

**Comment by mcallistersean** [comment]
Correct, I don't intend to push every small change to production. 
But the landing page is better than what it was, so it's now on the production server.

**Comment by LauraPirgie** [comment]
Thanks Sean!

**Comment by ejochum** [comment]
It seems that in iOS the Safari browser doesn’t recognize the device correctly/doesn’t take over responsive behaviour (screenshot below).
![img_0034](https://cloud.githubusercontent.com/assets/25815769/23602299/33ea7888-0250-11e7-8be0-4cfca3b68ba7.PNG)

On desktop, Safari displays properly when adapting the browser window dimensions (screenshot below).
<img width="505" alt="20170306_toucan_screenshot_safari" src="https://cloud.githubusercontent.com/assets/25815769/23602302/3654da64-0250-11e7-928e-4bd16cf4228f.png">

How do we solve this issue? Thx!

**Comment by mcallistersean** [comment]
Fixed on production server.
In the future please create a new issue or re-open an existing one.
