### ISSUE TITLE
Session issue on IOS

### ISSUE THREAD

**Issue by mcallistersean** [beetwo/toucan#69]
## Description

It seems that when using an Ios Device (Iphone) and adding Toucan to the homescreen a user needs to login every time he clicks on the Icon.

## Explanation
This relates to session handling which by default is set to session length. Checking the Remember me box during login should set this to 2 weeks. 

## Solution
I'd need some help from an Iphone user (@LauraPirgie) to confirm this.
*Please login using the checkbox and see if things work for you?*

**Comment by LauraPirgie** [comment]
It works!
