### ISSUE TITLE
UN Ocha Icons

### ISSUE THREAD

**Issue by mcallistersean** [beetwo/toucan#74]
We need to implement the icons from the attached pdf.
This issue tracks the progess on this.

[170804_beetwo_toucan_category-icons.pdf](https://github.com/beetwo/toucan/files/1202382/170804_beetwo_toucan_category-icons.pdf)

**Comment by mcallistersean** [comment]
These are the slugs that need to be resolved to the correct icons:
'core-relief-item', 'shelter', 'health', 'nutrition', 'sanitation-water-hygiene', 'logistics', 'protection', 'legal-advice', 'education', 'camp-management'

**Comment by mcallistersean** [comment]
@fadr 
I just fixed the mapping in the JS parts and found the following problems

- database slug name and icon names do not match:
  "core-relief-item": "core-relief-items"
   "sanitation-water-hygiene": "water-hygiene"

- No icon available?
  shelter

So we need to fix the missing icon and perhaps rename the 2 icons.

**Comment by mcallistersean** [comment]
if this c9d5eb1 is all that was need to rename the classes then part one is done.

**Comment by fadr** [comment]
Yes this is all that is needed for part one. Part two is in my next commit.

**Comment by fadr** [comment]
This 22a38bf6f5e331aa472f2cc250177a1da449690f should fix part two.
