### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by mcallistersean** [beetwo/toucan#83]
These are some open issues/feature requests that I will have to deal with in the next days.
Source: @fadr via slack 

 -----

# Toucan Progammierhilfe
- ~~Add Need / I can pick it up by myself~~
→ ~~eintrag in der db~~ und display auf der issue detail seite (da mag vielleicht emanuel auch noch was dazu sagen)
→ einbau in die filter

- Issue Status (open/in progress/resolved)
→ ~~db und verknüpfung mit dem dropdown auf der issue detail seite~~
→ ~~dann kann auch der resolve button weg~~  (da ist allerdings dann noch offen wie man eine resolve Nachricht eingibt)

- ~~Kategorie~~
→ ~~nur eine erlauben beim erstellen~~

- Filters
→ ~~Labels sind jetzt die CSS Klassen~~
→ ~~Reset sollte die Filter zurücksetzen (das kann man sonst auch erst mal ausblenden)~~
→ ~~Beim Filter sollte eine Zahl mit der Auswahl daneben stehen wenn Filter ausgewählt sind~~

- Listen 
→ Sorting ist noch nicht implementiert
→ ~~Wenn man auf den MapHandle klickt sollte die Klasse .listExpanded an .app-container angehängt werden.~~

- ~~Add meta tag~~

- ~~Cancel buttons für Formulare~~ 
→ ~~Sollte auf die vorherige Seite zurückspringen, wenn das geht?~~

**Comment by mcallistersean** [comment]
Update des Issue mit den erledigten Punkten.
Aber listExpanded Klasse macht nicht viel

**Comment by fadr** [comment]
Cancel buttons are now in place as well.

**Comment by mcallistersean** [comment]
2 things left to do from this list:
- filter by "pick up" flag => this would mean that we have to show it in the list, this is probably not really necessary
- sorting, see: #103
