### ISSUE TITLE
Landingpage Toucan Logo

### ISSUE THREAD

**Issue by LauraPirgie** [beetwo/toucan#90]
Enlarge Logo Toucan Logo: https://toucan.beetwo.at/

**Comment by mcallistersean** [comment]
That page is running the legacy version. 
Please submit bugs against https://toucan.brickwall.at/
The logo there is much larger.

**Comment by LauraPirgie** [comment]
Da die Landingpage auf toucan.beetwo.at der erste Link ist, den neue Nutzer im Moment von uns bekommen (request acces ist derzeit nur hier möglich, richtig?) würde ich Thomas bitten, das Logo groß einzubetten.

**Comment by mcallistersean** [comment]
Ok, I wasn't aware that anyone was still using that.

**Comment by mcallistersean** [comment]
Fixed and deployed, see 64ba11657608f39714f1eaa2b261fa2c9217f8f3
