### ISSUE TITLE
Fix map marker for create new need

### ISSUE THREAD

**Issue by fadr** [beetwo/toucan#97]
It’s too big and imprecise.

![screen shot 2017-09-14 at 17 32 02](https://user-images.githubusercontent.com/34631/30438867-979390b8-9972-11e7-93f2-1bc1ffd09255.png)

**Comment by mcallistersean** [comment]
Which browser are you using? Looks ok for me on chrome.

Are the icon element styles similar for you? The transform offsets look quite large to me.

```
<img src="..." 
class="leaflet-marker-icon leaflet-zoom-animated leaflet-interactive leaflet-marker-draggable" tabindex="0" 
style="transform: translate3d(282px, -283px, 0px); z-index: -283; outline: none;"
>
```

**Comment by fadr** [comment]
It was in Safari and I’ve seen it before, but it seems to work now. So I can’t recreate it. Nevermind!
